const houstonRadiusDistrictsAll: string[] = [
  "Aldine Independent School District",
  "Alief Independent School District",
  "Alvin Independent School District",
  "Angleton Independent School District",
  "Anahuac Independent School District",
  "Aristoi Classical Academy",
  "Brazosport Independent School District",
  "Channelview Independent School District",
  "Clear Creek Independent School District",
  "Crosby Independent School District",
  "Cypress-Fairbanks Independent School District",
  "Deer Park Independent School District",
  "Dickinson Independent School District",
  "Friendswood Independent School District",
  "Galena Park Independent School District",
  "Goose Creek Consolidated Independent School District",
  "Houston Independent School District",
  "Huffman Independent School District",
  "Humble Independent School District",
  "Katy Independent School District",
  "KIPP Texas Public Schools",
  "La Porte Independent School District",
  "Pasadena Independent School District",
  "Pearland Independent School District",
  "Spring Independent School District",
  "Spring Branch Independent School District",
  "Tomball Independent School District",
  "Fort Bend Independent School District",
  "Lamar Consolidated Independent School District",
  "Sheldon Independent School District",
  "New Caney Independent School District",
  "Royal Independent School District",
  "Santa Fe Independent School District",
  "YES Prep Public Schools",
  "Houston Gateway Academy"
];
